"use strict";
Object.assign(exports, require('./make-cache-manager-store.js'));
Object.assign(exports, require('./make-in-memory-store.js'));
Object.assign(exports, require('./make-ordered-dictionary.js'));
Object.assign(exports, require('./object-repository.js'));
Object.assign(exports, require('./keyed-db.js'));
const _reexport___make_cache_manager_store_js = require('./make-cache-manager-store.js');
exports.makeCacheManagerStore = _reexport___make_cache_manager_store_js.default;
const _reexport___make_in_memory_store_js = require('./make-in-memory-store.js');
exports.makeInMemoryStore = _reexport___make_in_memory_store_js.default;
const _reexport___make_ordered_dictionary_js = require('./make-ordered-dictionary.js');
exports.makeOrderedDictionary = _reexport___make_ordered_dictionary_js.default;
const _reexport___object_repository_js = require('./object-repository.js');
exports.objectRepository = _reexport___object_repository_js.default;
const _reexport___keyed_db_js = require('./keyed-db.js');
exports.keyedDB = _reexport___keyed_db_js.default;